namespace SceneTalkVR.Core
{
    public enum SceneTalkState
    {
        Idle,
        Settings,
        ExperimentMenu,
        ExperimentPhase,
        ExperimentPhaseCompleted,
        ExperimentExitConfirm,
        ExperimentHistoryLoading,
        ExperimentHistoryList,
        ExperimentHistoryActions,
        ExperimentHistoryRecord,
        ExperimentHistoryConversationDetail,
        ExperimentHistoryQuestionnaireDetail,
        ExperimentHistoryDeleteConfirm,
        ExperimentHistoryError,
        HistoryLoading,
        HistoryList,
        HistoryDetail,
        HistoryDeleteConfirm,
        HistoryRestoring,
        HistoryError,
        Listening,
        Recording,
        Transcribing,
        Processing,
        SceneReady,
        AvatarSpeaking,
        CorrectionFeedbackSpeaking,
        DialogueSpeaking,
        TurnReview,
        Questionnaire,
        Finished,
        Error
    }
}
