using System;
using System.Collections;
using System.Linq;
using System.Reflection;
using NUnit.Framework;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
using UnityEngine.UI;

namespace SceneTalkVR.Tests.PlayMode
{
    public sealed class RehearsalPlayModeTests
    {
        private Component rehearsal;
        [UnitySetUp] public IEnumerator SetUp(){if(SceneManager.GetActiveScene().name!="SampleScene"){SceneManager.LoadScene("SampleScene");yield return null;}yield return null;rehearsal=Create();}
        [UnityTearDown] public IEnumerator TearDown(){SetPicoDeviceValidation(false);if(rehearsal!=null){rehearsal.GetType().GetMethod("ResetSession").Invoke(rehearsal,null);UnityEngine.Object.Destroy(rehearsal);}yield return null;}
        [UnityTest] public IEnumerator T01_CoordinatorUsesRehearsalProtocol(){Assert.That(Get(Get("Protocol"),"ProtocolVersion"),Is.EqualTo("1.1-rehearsal-2"));yield return null;}
        [UnityTest] public IEnumerator T02_FormalSessionHasCollectionEquivalentIdentity(){Start("CreateFormalSession","P-FORMAL-01","S-01");AssertIsolation(Get("FormalAssignment"),"Formal");yield return null;}
        [UnityTest] public IEnumerator T03_PilotSessionHasCollectionEquivalentIdentity(){Start("CreatePilotSession","P-PILOT-01","S-01");AssertIsolation(Get("PilotAssignment"),"Pilot");yield return null;}
        [UnityTest] public IEnumerator T04_FormalUsesFourConditionLifecycle(){Start("CreateFormalSession","P-FORMAL-02","S-02");Assert.That(Count(Get(Get("FormalAssignment"),"conditions")),Is.EqualTo(4));Call("PrepareCurrentCondition");Assert.That(Count(Get(Get(Find("SceneTalkVR.Core.ExperimentLifecycleCoordinator, Assembly-CSharp"),"GoalTracker"),"Goals")),Is.EqualTo(4));yield return null;}
        [UnityTest] public IEnumerator T05_PilotUsesThreeConditionWorkflow(){Start("CreatePilotSession","P-PILOT-02","S-02");Assert.That(Count(Get(Get("PilotAssignment"),"conditions")),Is.EqualTo(3));Call("PrepareCurrentCondition");Assert.That(Get("CurrentTaskId") as string,Does.StartWith("pilot_restaurant_"));yield return null;}
        [UnityTest] public IEnumerator T06_VoiceOnlyIsHeadLockedAndInvisible(){var p=Profile("VoiceOnly");Assert.That(Get(p,"visualMode").ToString(),Is.EqualTo("None"));Assert.That(Get(p,"audioSourcePolicy").ToString(),Is.EqualTo("NonSpatialHeadLocked"));Assert.That((float)Get(p,"spatialBlend"),Is.Zero);yield return null;}
        [UnityTest] public IEnumerator T07_OrbUsesGeneratedOrb(){var p=Profile("FloatingOrb");Assert.That(Get(p,"visualMode").ToString(),Is.EqualTo("FloatingOrb"));Assert.That(Get(p,"visualPrefabKey"),Is.EqualTo("generated_orb_v1"));yield return null;}
        [UnityTest] public IEnumerator T08_HumanoidNeverFallsBackToOrb(){var p=Profile("HumanoidAgent");Assert.That(Get(p,"visualMode").ToString(),Is.EqualTo("Humanoid"));Assert.That(Get(p,"visualPrefab"),Is.Not.Null);Assert.That(Get(p,"visualPrefabKey"),Is.EqualTo("teacher_female_humanoid_v1"));yield return null;}
        [UnityTest] public IEnumerator T09_ParticipantViewHasNoDemoBannerOrInternalStatus(){Start("CreateFormalSession","P-UI-01","S-UI");yield return null;var banner=GameObject.Find("EditorDemoBanner");var status=GameObject.Find("EditorDemoStatusPanel");Assert.That(banner==null||!banner.activeInHierarchy,Is.True);Assert.That(status==null||!status.activeInHierarchy,Is.True);}
        [UnityTest] public IEnumerator T10_ParticipantModeSelectionReplacesTaskSelection(){Start("CreateFormalSession","P-UI-02","S-UI");yield return null;var modes=GameObject.Find("FormalModeSelectionPanel");var selection=GameObject.Find("TaskSelectionPanel");Assert.That(modes,Is.Not.Null);Assert.That(modes.activeInHierarchy,Is.True);Assert.That(selection==null||!selection.activeInHierarchy,Is.True);}
        [UnityTest] public IEnumerator T11_ResetClearsAssignmentsAndGoals(){Start("CreateFormalSession","P-RESET","S-R");Call("PrepareCurrentCondition");rehearsal.GetType().GetMethod("ResetSession").Invoke(rehearsal,null);Assert.That((bool)Get("IsActive"),Is.False);Assert.That(Get("FormalAssignment"),Is.Null);Assert.That(Count(Get(Get(Find("SceneTalkVR.Core.ExperimentLifecycleCoordinator, Assembly-CSharp"),"GoalTracker"),"Goals")),Is.Zero);yield return null;}
        [UnityTest] public IEnumerator T12_FormalSharesLifecycleCoordinator(){var field=rehearsal.GetType().GetField("formalLifecycle",BindingFlags.Instance|BindingFlags.NonPublic);Assert.That(field.FieldType.FullName,Is.EqualTo("SceneTalkVR.Core.ExperimentLifecycleCoordinator"));yield return null;}
        [UnityTest] public IEnumerator T13_PilotSharesWorkflowCoordinator(){var field=rehearsal.GetType().GetField("pilotWorkflow",BindingFlags.Instance|BindingFlags.NonPublic);Assert.That(field.FieldType.FullName,Is.EqualTo("SceneTalkVR.Core.PilotWorkflowCoordinator"));yield return null;}
        [UnityTest] public IEnumerator T14_LegacyDemoCannotCreateNewSession(){var manager=Find("SceneTalkVR.Core.ExperimentConditionManager, Assembly-CSharp");var type=Type.GetType("SceneTalkVR.Core.EditorDemoSessionCoordinator, Assembly-CSharp");var legacy=(Component)manager.gameObject.AddComponent(type);var args=new object[]{"OLD",null};Assert.That((bool)type.GetMethod("StartFormalDemo").Invoke(legacy,args),Is.False);Assert.That(args[1] as string,Does.Contain("legacy_editor_demo_creation_disabled"));UnityEngine.Object.Destroy(legacy);yield return null;}
        [UnityTest] public IEnumerator T15_QualificationDoesNotDependOnIdPrefix(){Start("CreateFormalSession","any-project-test-id","session-x");Assert.That(Get("ParticipantId"),Is.EqualTo("any-project-test-id"));Assert.That(Get(Get("RuntimeContext"),"qualification").ToString(),Is.EqualTo("Rehearsal"));yield return null;}
        [UnityTest] public IEnumerator T16_FormalAvatarMappingIsExplicit(){Assert.That(Invoke("ResolveFormalAvatarKey","hotel_check_in"),Is.EqualTo("barista_male_humanoid_v1"));Assert.That(Invoke("ResolveFormalAvatarKey","tourist_assistance"),Is.EqualTo("barista_male_humanoid_v1"));yield return null;}
        [UnityTest] public IEnumerator T17_QaGoalsAreExplicitlyTracked(){Start("CreateFormalSession","P-QA","S-QA");Call("PrepareCurrentCondition");Call("CompleteCurrentGoalsForQa");Assert.That((bool)Get(Get(Find("SceneTalkVR.Core.ExperimentLifecycleCoordinator, Assembly-CSharp"),"GoalTracker"),"AreAllConfirmed"),Is.True);yield return null;}
        [UnityTest] public IEnumerator T18_ParticipantSelectsConditionWithoutSeeingTask(){Start("CreateFormalSession","P-CHOICE","S-C");yield return null;var panel=GameObject.Find("FormalModeSelectionPanel");var labels=panel.GetComponentsInChildren<TMP_Text>(true).Select(x=>x.text).ToArray();Assert.That(labels.Any(x=>x.Contains("hotel_check_in")||x.Contains("Hotel Check-In")),Is.False);Select("NE",true);Assert.That(Get("CurrentTaskId") as string,Is.Not.Empty);yield return null;}
        [UnityTest] public IEnumerator T19_DoubleSelectionIsGuarded(){Start("CreateFormalSession","P-DOUBLE","S-D");Select("NE",true);Select("NR",false,"formal_condition_selection_in_progress");yield return null;}
        [UnityTest] public IEnumerator T20_SelectionOrderIsPersisted(){Start("CreateFormalSession","P-ORDER","S-O");Select("SR",true);var order=Get(Get("FormalAssignment"),"participantSelectionOrder");Assert.That(Count(order),Is.EqualTo(1));Assert.That(((Array)order).GetValue(0).ToString(),Is.EqualTo("SR"));yield return null;}
        [UnityTest] public IEnumerator T21_PicoDeviceValidationHidesValidationOverlays(){SetPicoDeviceValidation(true);yield return null;var banner=GameObject.Find("EditorDemoBanner");var status=GameObject.Find("EditorDemoStatusPanel");Assert.That(banner==null||!banner.activeInHierarchy,Is.True);Assert.That(status==null||!status.activeInHierarchy,Is.True);}

        private Component Create(){var manager=Find("SceneTalkVR.Core.ExperimentConditionManager, Assembly-CSharp");Assert.That(manager,Is.Not.Null);var type=Type.GetType("SceneTalkVR.Core.RehearsalSessionCoordinator, Assembly-CSharp");var value=manager.GetComponent(type)??manager.gameObject.AddComponent(type);var configure=type.GetMethod("Configure");var ps=configure.GetParameters();configure.Invoke(value,new[]{Asset("Assets/SceneTalkVR/ExperimentProtocol/ExperimentV11RehearsalProtocol.asset",ps[0].ParameterType),Asset("Assets/SceneTalkVR/ExperimentProtocol/ExperimentV11RehearsalResources.asset",ps[1].ParameterType),Asset("Assets/SceneTalkVR/ExperimentProtocol/ExperimentV11RehearsalVoiceProfileCatalog.asset",ps[2].ParameterType),Asset("Assets/SceneTalkVR/ExperimentProtocol/ExperimentV11RehearsalDeploymentCatalog.asset",ps[3].ParameterType)});return(Component)value;}
        private void Start(string method,string participant,string session){var args=new object[]{participant,session,null};Assert.That((bool)rehearsal.GetType().GetMethod(method).Invoke(rehearsal,args),Is.True,args[2] as string);}
        private void Call(string method){var args=new object[]{null};Assert.That((bool)rehearsal.GetType().GetMethod(method).Invoke(rehearsal,args),Is.True,args[0] as string);}
        private object Profile(string name){var m=rehearsal.GetType().GetMethod("ResolvePilotProfile");return m.Invoke(rehearsal,new[]{Enum.Parse(m.GetParameters()[0].ParameterType,name)});}
        private object Invoke(string method,params object[] args)=>rehearsal.GetType().GetMethod(method).Invoke(rehearsal,args);
        private void Select(string code,bool expected,string expectedError=null){var method=rehearsal.GetType().GetMethod("SelectFormalCondition");var args=new object[]{Enum.Parse(method.GetParameters()[0].ParameterType,code),null};Assert.That((bool)method.Invoke(rehearsal,args),Is.EqualTo(expected),args[1] as string);if(expectedError!=null)Assert.That(args[1] as string,Does.Contain(expectedError));}
        private object Get(string name)=>Get(rehearsal,name);
        private static object Get(object value,string name){if(value==null)return null;var t=value.GetType();return t.GetProperty(name,BindingFlags.Public|BindingFlags.Instance)?.GetValue(value)??t.GetField(name,BindingFlags.Public|BindingFlags.Instance)?.GetValue(value);}
        private static int Count(object value){if(value is ICollection c)return c.Count;var p=value?.GetType().GetProperty("Count")??value?.GetType().GetProperty("Length");return p==null?0:(int)p.GetValue(value);}
        private static Component Find(string name){var t=Type.GetType(name);return(Component)Resources.FindObjectsOfTypeAll(t).FirstOrDefault();}
        private static void SetPicoDeviceValidation(bool value){var type=Type.GetType("SceneTalkVR.Core.ExperimentRuntimePlatform, Assembly-CSharp");type.GetProperty("ForcePicoDeviceValidationForTests",BindingFlags.Public|BindingFlags.Static).SetValue(null,value);}
        private static object Asset(string path,Type type){var adb=Type.GetType("UnityEditor.AssetDatabase, UnityEditor");return adb.GetMethod("LoadAssetAtPath",new[]{typeof(string),typeof(Type)}).Invoke(null,new object[]{path,type});}
        private static void AssertIsolation(object a,string flow){Assert.That(Get(a,"flowMode").ToString(),Is.EqualTo(flow));Assert.That(Get(a,"runQualification").ToString(),Is.EqualTo("Rehearsal"));Assert.That(Get(a,"dataOrigin"),Is.EqualTo("rehearsal"));Assert.That((bool)Get(a,"collectionEligible"),Is.False);Assert.That((bool)Get(a,"developerTestAssignment"),Is.False);Assert.That((bool)Get(a,"demoMode"),Is.False);}
    }
}
