using System;
using System.Collections;
using System.Linq;
using NUnit.Framework;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
using UnityEngine.UI;

namespace SceneTalkVR.Tests.PlayMode
{
    public sealed class PilotCollectionParticipantFlowPlayModeTests
    {
        [UnitySetUp]public IEnumerator SetUp(){ForcePicoDeviceValidation(false);ResetUserSettings();if(SceneManager.GetActiveScene().name!="SampleScene"){SceneManager.LoadScene("SampleScene");yield return null;}yield return null;CallActive("SceneTalkVR.Core.EditorCollectionSessionCoordinator, Assembly-CSharp","EndRuntimeSession");CallActive("SceneTalkVR.Core.RehearsalSessionCoordinator, Assembly-CSharp","ResetSession");}
        [UnityTearDown]public IEnumerator TearDown(){CallActive("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp","ResetPilotSessionForQa");CallActive("SceneTalkVR.Core.ExperimentSessionCoordinator, Assembly-CSharp","ConfirmLeaveExperiment");ForcePicoDeviceValidation(false);ResetUserSettings();yield return null;}
        [UnityTest]public IEnumerator MainMenu_HasIndependentFormalAndPilotRoutes()
        {Assert.That(Label("NewExperimentButton"),Is.EqualTo("New Experiment"));Assert.That(Label("ExperimentHistoryButton"),Is.EqualTo("Experiment History"));AssertHomeNavigation();Click("NewExperimentButton");yield return null;Assert.That(Active("ExperimentMenuPanel"),Is.True);Assert.That(Button("EnterPilotButton").interactable,Is.True);Assert.That(Button("EnterFormalButton").interactable,Is.False);Click("EnterPilotButton");yield return null;Assert.That(Active("PilotInstructionsPanel"),Is.True);Assert.That(Active("PilotSessionSetupPanel"),Is.False);Assert.That(Active("FormalModeSelectionPanel"),Is.False);Assert.That(Active("TaskSelectionPanel"),Is.False);AssertExitOverlay();}
        [UnityTest]public IEnumerator PilotCreateSession_PersistsBalancedAssignmentAndShowsInstructions()
        {Create();yield return null;var coordinator=ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp");Assert.That((bool)Get(coordinator,"IsArmed"),Is.True);Assert.That(Get(coordinator,"Stage").ToString(),Is.EqualTo("Instructions"));Assert.That((string)Get(coordinator,"ParticipantId"),Does.StartWith("EXP-P-"));Assert.That((string)Get(coordinator,"SessionId"),Does.EndWith("-pilot"));var assignment=Get(coordinator,"Assignment");Assert.That((bool)Get(assignment,"collectionEligible"),Is.True);Assert.That((bool)Get(assignment,"developerTestAssignment"),Is.False);var conditions=((IEnumerable)Get(assignment,"conditions")).Cast<object>().ToArray();Assert.That(conditions.Select(x=>Get(Get(x,"task"),"taskId")).Distinct().Count(),Is.EqualTo(3));Assert.That(conditions.Select(x=>Get(x,"embodimentCondition")).Distinct().Count(),Is.EqualTo(3));Assert.That(System.IO.File.Exists(System.IO.Path.Combine((string)Get(coordinator,"CurrentDataFolder"),"pilot_assignment.json")),Is.True);Assert.That(Active("PilotInstructionsPanel"),Is.True);}
        [UnityTest]public IEnumerator IncompleteExperimentMenuExitRequiresConfirmationAndKeepsRecord()
        {Click("NewExperimentButton");yield return null;var experiment=ActiveObject("SceneTalkVR.Core.ExperimentSessionCoordinator, Assembly-CSharp");var id=(string)Get(Get(Get(experiment,"CurrentExperiment"),"summary"),"experimentId");Click("ExitButton");yield return null;Assert.That(Active("ExperimentExitConfirmPanel"),Is.True);Click("ContinueExperimentButton");yield return null;Assert.That(Active("ExperimentMenuPanel"),Is.True);Click("ExitButton");yield return null;Click("ConfirmExitExperimentButton");yield return null;AssertHomeNavigation();Click("ExperimentHistoryButton");yield return null;Assert.That(Active("ExperimentHistoryListPanel"),Is.True);var items=((IEnumerable)Get(Get(experiment,"CurrentHistoryPage"),"items")).Cast<object>();Assert.That(items.Any(x=>(string)Get(x,"experimentId")==id),Is.True);}
        [UnityTest]public IEnumerator BeginPilot_ShowsAssignedTaskWithoutEmbodimentMetadata()
        {Create();Click("BeginPilotButton");yield return null;Assert.That(Active("PilotConditionTaskIntroductionPanel"),Is.True);var text=Text("PilotConditionTaskIntroductionPanel");Assert.That(text,Does.Contain("Communication goals:"));Assert.That(text,Does.Not.Contain("voice_only"));Assert.That(text,Does.Not.Contain("floating_orb"));Assert.That(text,Does.Not.Contain("humanoid_agent"));Click("PilotTaskContinueButton");yield return new WaitForSecondsRealtime(1f);Assert.That(Active("ReadOnlyTaskGoalPanel"),Is.True);AssertTaskAboveFullWidthDialogue();SetHideDialogueSubtitles(true);yield return null;AssertTaskAboveFullWidthDialogue();SetHideDialogueSubtitles(false);yield return null;var coordinator=ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp");var task=Get(coordinator,"CurrentTask");var orchestrator=ActiveObject("SceneTalkVR.Runtime.SceneTalkOrchestrator, Assembly-CSharp");var payload=Get(orchestrator,"LastScenePayload");Assert.That(Get(task,"taskId"),Is.EqualTo("pilot_restaurant_walk_in"));Assert.That(Get(payload,"taskType"),Is.EqualTo("pilot_restaurant_walk_in"));Assert.That(Get(payload,"dialogueReply"),Is.EqualTo("Good evening! Welcome to Riverside Restaurant. Do you have a reservation?"));}
        [UnityTest]public IEnumerator VoiceOnlyPresenter_HasNoVisualAndResetDoesNotLeak()
        {var manager=(Component)ActiveObject("SceneTalkVR.Core.ExperimentConditionManager, Assembly-CSharp");var presenterType=Type.GetType("SceneTalkVR.AvatarSystem.PilotEmbodimentPresenter, Assembly-CSharp");var presenter=manager.GetComponent(presenterType)??manager.gameObject.AddComponent(presenterType);var catalog=Get(manager,"PilotPresentationCatalog");var embodiment=Enum.Parse(Type.GetType("SceneTalkVR.Core.PilotEmbodimentCondition, Assembly-CSharp"),"VoiceOnly");var profile=catalog.GetType().GetMethod("Find").Invoke(catalog,new[]{embodiment});var policy=Enum.Parse(Type.GetType("SceneTalkVR.Core.PilotAudioSourcePolicy, Assembly-CSharp"),"NonSpatialHeadLocked");var args=new[]{profile,policy,(object)true,null};Assert.That((bool)presenterType.GetMethod("Configure").Invoke(presenter,args),Is.True,args[3] as string);presenterType.GetMethod("BeginFeedback").Invoke(presenter,null);Assert.That((bool)Get(presenter,"HasVisualEntity"),Is.False);Assert.That(((AudioSource)Get(presenter,"AudioSource")).spatialBlend,Is.Zero);presenterType.GetMethod("ResetSession").Invoke(presenter,null);Assert.That((bool)Get(presenter,"HasVisualEntity"),Is.False);yield return null;}
        [UnityTest]public IEnumerator CompleteControlledParticipantFlow_ReachesRankingAndCompletion()
        {Create();AssertExitOverlay();Click("BeginPilotButton");yield return null;AssertExitOverlay();var phrases=new[]{new[]{"No, I don't have a reservation.","There are four of us.","Do you have a table available?","How long is the wait?"},new[]{"What do you recommend?","I'd like the grilled chicken.","I don't eat seafood.","I'd like a glass of water."},new[]{"This isn't what I ordered.","I ordered the beef pasta.","Could you replace it, please?","How long will the replacement take?"}};for(var condition=0;condition<3;condition++){Click("PilotTaskContinueButton");yield return null;AssertExitOverlay();foreach(var phrase in phrases[condition])EvaluatePilot(phrase);yield return new WaitForSecondsRealtime(1f);Assert.That(Active("PilotQuestionnairePanel"),Is.True);AssertExitOverlay();foreach(var item in new[]{"pilot_rc_01","pilot_sc_01","pilot_accept_01"})Click(item+"_4");Click("PilotQuestionnaireSubmitButton");yield return null;if(condition<2){Assert.That(Active("PilotNeutralTransitionPanel"),Is.True);AssertExitOverlay();Click("PilotTransitionContinueButton");yield return null;AssertExitOverlay();}}Assert.That(Active("PilotFinalRankingPanel"),Is.True);AssertExitOverlay();Click("VoiceOnlyRank1");Click("FloatingOrbRank2");Click("HumanoidAgentRank3");AssertRankSelected("VoiceOnlyRank1");AssertRankSelected("FloatingOrbRank2");AssertRankSelected("HumanoidAgentRank3");Click("FloatingOrbRank1");AssertRankSelected("VoiceOnlyRank2");AssertRankSelected("FloatingOrbRank1");AssertRankSelected("HumanoidAgentRank3");AssertRankNotSelected("VoiceOnlyRank1");AssertRankNotSelected("FloatingOrbRank2");Click("VoiceOnlyRank1");AssertRankSelected("VoiceOnlyRank1");AssertRankSelected("FloatingOrbRank2");AssertRankSelected("HumanoidAgentRank3");Click("VoiceOnlyPreferred");Input("PilotRankingReason").text="The feedback was easiest to follow.";Click("PilotRankingSubmitButton");yield return null;Assert.That(Active("PilotExperimentCompletionPanel"),Is.True);AssertExitOverlay();var coordinator=ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp");var exportArgs=new object[]{null};Assert.That((bool)coordinator.GetType().GetMethod("ExportBundle").Invoke(coordinator,exportArgs),Is.True,exportArgs[0] as string);var auditArgs=new object[]{null};Assert.That((bool)coordinator.GetType().GetMethod("AuditBundle").Invoke(coordinator,auditArgs),Is.True,auditArgs[0] as string);Click("PilotCompletionContinueButton");yield return null;Assert.That(Active("ExperimentMenuPanel"),Is.True);Assert.That(Button("EnterPilotButton").interactable,Is.False);Assert.That(Button("EnterFormalButton").interactable,Is.True);}
        [UnityTest]public IEnumerator GlobalExit_SuspendsAndPersistsPilotExperimentSession()
        {
            Create();Click("BeginPilotButton");yield return null;Click("PilotTaskContinueButton");yield return null;
            var coordinator=ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp");
            var workflow=Get(coordinator,"Workflow");var current=Get(workflow,"Current");var dataFolder=(string)Get(coordinator,"CurrentDataFolder");
            AssertExitOverlay();Click("ExitButton");yield return null;
            Assert.That(Active("ExperimentMenuPanel"),Is.True);Assert.That((bool)Get(coordinator,"IsArmed"),Is.False);Assert.That(Get(coordinator,"Stage").ToString(),Is.EqualTo("None"));
            Assert.That(Get(current,"status").ToString(),Is.EqualTo("TechnicalInvalid"));
            var events=System.IO.File.ReadAllText(System.IO.Path.Combine(dataFolder,"pilot_collection_operator_events.jsonl"));
            Assert.That(events,Does.Contain("PilotSessionSuspended"));Assert.That(events,Does.Contain("\"actor\":\"participant\""));
        }
        [UnityTest]public IEnumerator PicoDeviceValidation_CompletesPilotWithoutCollectionEligibility()
        {
            ForcePicoDeviceValidation(true);Create();yield return null;
            var coordinator=ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp");
            Assert.That((bool)Get(coordinator,"IsDeviceValidation"),Is.True);Assert.That((bool)Get(coordinator,"IsArmed"),Is.True);
            var context=Get(coordinator,"RuntimeContext");Assert.That((bool)Get(context,"collectionEligible"),Is.False);Assert.That(Get(context,"dataOrigin"),Is.EqualTo("rehearsal"));Assert.That(Get(context,"deploymentProfile"),Is.EqualTo("pico_device_validation"));
            Click("BeginPilotButton");yield return null;
            for(var condition=0;condition<3;condition++){Click("PilotTaskContinueButton");yield return null;CompletePilotGoalsForQa(coordinator);yield return new WaitForSecondsRealtime(1f);foreach(var item in new[]{"pilot_rc_01","pilot_sc_01","pilot_accept_01"})Click(item+"_4");Click("PilotQuestionnaireSubmitButton");yield return null;if(condition<2){Click("PilotTransitionContinueButton");yield return null;}}
            Click("VoiceOnlyRank1");Click("FloatingOrbRank2");Click("HumanoidAgentRank3");Click("VoiceOnlyPreferred");Input("PilotRankingReason").text="Device validation ranking.";Click("PilotRankingSubmitButton");yield return null;
            Assert.That(Active("PilotExperimentCompletionPanel"),Is.True);Assert.That((bool)Get(Get(coordinator,"Assignment"),"collectionEligible"),Is.False);
            var rehearsal=ActiveObject("SceneTalkVR.Core.RehearsalSessionCoordinator, Assembly-CSharp");Assert.That((bool)Get(rehearsal,"ExperimentCompleted"),Is.True);
        }
        [UnityTest]public IEnumerator SuspendedPilotResumesAtIntroductionAndCreatesNewAttempt()
        {
            Create();Click("BeginPilotButton");yield return null;Click("PilotTaskContinueButton");yield return null;
            var pilot=ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp");var first=(int)Get(Get(Get(pilot,"Workflow"),"Current"),"runAttempt");
            Click("ExitButton");yield return null;Assert.That(Active("ExperimentMenuPanel"),Is.True);Click("EnterPilotButton");yield return null;
            Assert.That(Active("PilotConditionTaskIntroductionPanel"),Is.True);Click("PilotTaskContinueButton");yield return null;
            var second=(int)Get(Get(Get(pilot,"Workflow"),"Current"),"runAttempt");Assert.That(second,Is.EqualTo(first+1));
            var experiment=ActiveObject("SceneTalkVR.Core.ExperimentSessionCoordinator, Assembly-CSharp");var attempts=((IEnumerable)Get(Get(experiment,"CurrentExperiment"),"attempts")).Cast<object>().ToArray();
            Assert.That(attempts,Has.Length.EqualTo(2));Assert.That(Get(attempts[0],"status").ToString(),Is.EqualTo("Suspended"));Assert.That(Get(attempts[1],"status").ToString(),Is.EqualTo("Running"));
        }
        private static void Create(){Click("NewExperimentButton");Click("EnterPilotButton");}
        private static TMP_InputField Input(string name)=>Resources.FindObjectsOfTypeAll<TMP_InputField>().First(x=>x.name==name&&x.gameObject.scene.IsValid());
        private static Button Button(string name)=>Resources.FindObjectsOfTypeAll<Button>().First(x=>x.name==name&&x.gameObject.scene.IsValid());
        private static void Click(string name)=>Button(name).onClick.Invoke();
        private static void AssertRankSelected(string name)=>Assert.That(Button(name).GetComponent<Image>().color.g,Is.EqualTo(.68f).Within(.001f),name+" should remain selected.");
        private static void AssertRankNotSelected(string name)=>Assert.That(Button(name).GetComponent<Image>().color.g,Is.EqualTo(.38f).Within(.001f),name+" should not remain selected.");
        private static bool Active(string name)=>Resources.FindObjectsOfTypeAll<GameObject>().Any(x=>x.name==name&&x.gameObject.scene.IsValid()&&x.activeInHierarchy);
        private static string Label(string button)=>Button(button).GetComponentInChildren<TMP_Text>(true).text;
        private static string Text(string panel){var go=Resources.FindObjectsOfTypeAll<GameObject>().First(x=>x.name==panel&&x.scene.IsValid());return string.Join("\n",go.GetComponentsInChildren<TMP_Text>(true).Select(x=>x.text));}
        private static int EvaluatePilot(string transcript){var type=Type.GetType("SceneTalkVR.Core.GoalEvaluationOrchestrator, Assembly-CSharp");var pilot=Get(ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp"),"Workflow");return(int)type.GetMethod("EvaluatePilotUserTranscript").Invoke(null,new[]{pilot,Guid.NewGuid().ToString("N"),transcript,"participant"});}
        private static object Get(object value,string name){var type=value.GetType();return type.GetProperty(name)?.GetValue(value)??type.GetField(name)?.GetValue(value);}
        private static object ActiveObject(string typeName){var type=Type.GetType(typeName);return Resources.FindObjectsOfTypeAll(type).FirstOrDefault();}
        private static void CallActive(string typeName,string method){var value=ActiveObject(typeName);value?.GetType().GetMethod(method)?.Invoke(value,null);}
        private static void CompletePilotGoalsForQa(object coordinator){var args=new object[]{null};Assert.That((bool)coordinator.GetType().GetMethod("CompleteCurrentPilotGoalsForQa").Invoke(coordinator,args),Is.True,args[0] as string);}
        private static void ForcePicoDeviceValidation(bool value){var type=Type.GetType("SceneTalkVR.Core.ExperimentRuntimePlatform, Assembly-CSharp");type.GetProperty("ForcePicoDeviceValidationForTests").SetValue(null,value);}
        private static void ResetUserSettings(){var type=Type.GetType("SceneTalkVR.Core.SceneTalkUserSettingsStore, Assembly-CSharp");type.GetMethod("ResetAll").Invoke(null,null);}
        private static void SetHideDialogueSubtitles(bool hidden){var type=Type.GetType("SceneTalkVR.Core.SceneTalkUserSettingsStore, Assembly-CSharp");type.GetMethod("SetHideDialogueSubtitles").Invoke(null,new object[]{hidden});}
        private static void AssertTaskAboveFullWidthDialogue(){var task=Rect("ReadOnlyTaskGoalPanel");var dialogue=Rect("SubtitlePanel");var canvas=Resources.FindObjectsOfTypeAll<Canvas>().First(x=>x.gameObject.scene.IsValid()&&x.gameObject.name.StartsWith("SceneTalkVR World UI",StringComparison.Ordinal));var canvasRect=(RectTransform)canvas.transform;var taskLeft=task.anchoredPosition.x+task.rect.xMin;var taskTop=task.anchoredPosition.y+task.rect.yMax;var taskBottom=task.anchoredPosition.y+task.rect.yMin;var dialogueLeft=dialogue.anchoredPosition.x+dialogue.rect.xMin;var dialogueRight=dialogue.anchoredPosition.x+dialogue.rect.xMax;var dialogueTop=dialogue.anchoredPosition.y+dialogue.rect.yMax;var dialogueBottom=dialogue.anchoredPosition.y+dialogue.rect.yMin;Assert.That(taskBottom-dialogueTop,Is.GreaterThanOrEqualTo(20f),"Task goals must remain above the dialogue panel.");Assert.That(taskLeft,Is.GreaterThanOrEqualTo(canvasRect.rect.xMin));Assert.That(taskTop,Is.LessThanOrEqualTo(canvasRect.rect.yMax));Assert.That(task.anchoredPosition.x,Is.LessThan(0f));Assert.That(task.anchoredPosition.y,Is.GreaterThan(0f));Assert.That(dialogueLeft,Is.GreaterThanOrEqualTo(canvasRect.rect.xMin));Assert.That(dialogueRight,Is.LessThanOrEqualTo(canvasRect.rect.xMax));Assert.That(dialogueBottom,Is.GreaterThanOrEqualTo(canvasRect.rect.yMin));Assert.That(dialogue.rect.width,Is.GreaterThanOrEqualTo(800f),"Dialogue must use the full lower width.");Assert.That(dialogue.anchoredPosition.y,Is.LessThan(0f));}
        private static RectTransform Rect(string name)=>Resources.FindObjectsOfTypeAll<GameObject>().First(x=>x.name==name&&x.scene.IsValid()).GetComponent<RectTransform>();
        private static void AssertHomeNavigation(){Assert.That(Active("QuitButton"),Is.True);Assert.That(Label("QuitButton"),Is.EqualTo("Quit"));Assert.That(Button("QuitButton").transform.parent.gameObject.name,Is.EqualTo("InitialPanel"));Assert.That(Active("ExitButton"),Is.False,"The home page must use Quit instead of the global Exit button.");}
        private static void AssertExitOverlay(){var button=Button("ExitButton");var rect=button.GetComponent<RectTransform>();var canvas=Resources.FindObjectsOfTypeAll<Canvas>().First(x=>x.gameObject.scene.IsValid()&&x.gameObject.name.StartsWith("SceneTalkVR World UI",StringComparison.Ordinal));Assert.That(button.gameObject.activeInHierarchy,Is.True);Assert.That(button.transform.parent,Is.EqualTo(canvas.transform));Assert.That(button.transform.GetSiblingIndex(),Is.EqualTo(canvas.transform.childCount-1));Assert.That(rect.anchorMin,Is.EqualTo(Vector2.one));Assert.That(rect.anchorMax,Is.EqualTo(Vector2.one));Assert.That(rect.anchoredPosition.x,Is.LessThan(0f));Assert.That(rect.anchoredPosition.y,Is.LessThan(0f));Assert.That(Active("QuitButton"),Is.False);}
    }
}
