using System;
using System.Collections;
using System.Linq;
using NUnit.Framework;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
using UnityEngine.UI;

namespace SceneTalkVR.Tests.PlayMode
{
    public sealed class PilotCollectionParticipantFlowPlayModeTests
    {
        [UnitySetUp]public IEnumerator SetUp(){if(SceneManager.GetActiveScene().name!="SampleScene"){SceneManager.LoadScene("SampleScene");yield return null;}yield return null;CallActive("SceneTalkVR.Core.EditorCollectionSessionCoordinator, Assembly-CSharp","EndRuntimeSession");CallActive("SceneTalkVR.Core.RehearsalSessionCoordinator, Assembly-CSharp","ResetSession");}
        [UnityTearDown]public IEnumerator TearDown(){CallActive("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp","ResetPilotSessionForQa");yield return null;}
        [UnityTest]public IEnumerator MainMenu_HasIndependentFormalAndPilotRoutes()
        {Assert.That(Label("StartButton"),Is.EqualTo("Formal Experiment"));Assert.That(Label("PilotExperimentButton"),Is.EqualTo("Pilot Experiment"));Click("PilotExperimentButton");yield return null;Assert.That(Active("PilotInstructionsPanel"),Is.True);Assert.That(Active("PilotSessionSetupPanel"),Is.False);Assert.That(Active("FormalModeSelectionPanel"),Is.False);Assert.That(Active("TaskSelectionPanel"),Is.False);}
        [UnityTest]public IEnumerator PilotCreateSession_PersistsBalancedAssignmentAndShowsInstructions()
        {Click("PilotExperimentButton");yield return null;var coordinator=ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp");Assert.That((bool)Get(coordinator,"IsArmed"),Is.True);Assert.That(Get(coordinator,"Stage").ToString(),Is.EqualTo("Instructions"));Assert.That((string)Get(coordinator,"ParticipantId"),Does.StartWith("PILOT-P-"));Assert.That((string)Get(coordinator,"SessionId"),Does.StartWith("PILOT-S-"));var assignment=Get(coordinator,"Assignment");Assert.That((bool)Get(assignment,"collectionEligible"),Is.True);Assert.That((bool)Get(assignment,"developerTestAssignment"),Is.False);var conditions=((IEnumerable)Get(assignment,"conditions")).Cast<object>().ToArray();Assert.That(conditions.Select(x=>Get(Get(x,"task"),"taskId")).Distinct().Count(),Is.EqualTo(3));Assert.That(conditions.Select(x=>Get(x,"embodimentCondition")).Distinct().Count(),Is.EqualTo(3));Assert.That(System.IO.File.Exists(System.IO.Path.Combine((string)Get(coordinator,"CurrentDataFolder"),"pilot_assignment.json")),Is.True);Assert.That(Active("PilotInstructionsPanel"),Is.True);}
        [UnityTest]public IEnumerator BeginPilot_ShowsAssignedTaskWithoutEmbodimentMetadata()
        {Create();Click("BeginPilotButton");yield return null;Assert.That(Active("PilotConditionTaskIntroductionPanel"),Is.True);var text=Text("PilotConditionTaskIntroductionPanel");Assert.That(text,Does.Contain("Communication goals:"));Assert.That(text,Does.Not.Contain("voice_only"));Assert.That(text,Does.Not.Contain("floating_orb"));Assert.That(text,Does.Not.Contain("humanoid_agent"));Click("PilotTaskContinueButton");yield return new WaitForSecondsRealtime(1f);var coordinator=ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp");var task=Get(coordinator,"CurrentTask");var orchestrator=ActiveObject("SceneTalkVR.Runtime.SceneTalkOrchestrator, Assembly-CSharp");var payload=Get(orchestrator,"LastScenePayload");Assert.That(Get(task,"taskId"),Is.EqualTo("pilot_restaurant_walk_in"));Assert.That(Get(payload,"taskType"),Is.EqualTo("pilot_restaurant_walk_in"));Assert.That(Get(payload,"dialogueReply"),Is.EqualTo("Good evening! Welcome to Riverside Restaurant. Do you have a reservation?"));}
        [UnityTest]public IEnumerator VoiceOnlyPresenter_HasNoVisualAndResetDoesNotLeak()
        {var manager=(Component)ActiveObject("SceneTalkVR.Core.ExperimentConditionManager, Assembly-CSharp");var presenterType=Type.GetType("SceneTalkVR.AvatarSystem.PilotEmbodimentPresenter, Assembly-CSharp");var presenter=manager.GetComponent(presenterType)??manager.gameObject.AddComponent(presenterType);var catalog=Get(manager,"PilotPresentationCatalog");var embodiment=Enum.Parse(Type.GetType("SceneTalkVR.Core.PilotEmbodimentCondition, Assembly-CSharp"),"VoiceOnly");var profile=catalog.GetType().GetMethod("Find").Invoke(catalog,new[]{embodiment});var policy=Enum.Parse(Type.GetType("SceneTalkVR.Core.PilotAudioSourcePolicy, Assembly-CSharp"),"NonSpatialHeadLocked");var args=new[]{profile,policy,(object)true,null};Assert.That((bool)presenterType.GetMethod("Configure").Invoke(presenter,args),Is.True,args[3] as string);presenterType.GetMethod("BeginFeedback").Invoke(presenter,null);Assert.That((bool)Get(presenter,"HasVisualEntity"),Is.False);Assert.That(((AudioSource)Get(presenter,"AudioSource")).spatialBlend,Is.Zero);presenterType.GetMethod("ResetSession").Invoke(presenter,null);Assert.That((bool)Get(presenter,"HasVisualEntity"),Is.False);yield return null;}
        [UnityTest]public IEnumerator CompleteControlledParticipantFlow_ReachesRankingAndCompletion()
        {Create();Click("BeginPilotButton");yield return null;var phrases=new[]{new[]{"No, I don't have a reservation.","There are four of us.","Do you have a table available?","How long is the wait?"},new[]{"What do you recommend?","I'd like the grilled chicken.","I don't eat seafood.","I'd like a glass of water."},new[]{"This isn't what I ordered.","I ordered the beef pasta.","Could you replace it, please?","How long will the replacement take?"}};for(var condition=0;condition<3;condition++){Click("PilotTaskContinueButton");yield return null;foreach(var phrase in phrases[condition])EvaluatePilot(phrase);yield return new WaitForSecondsRealtime(1f);Assert.That(Active("PilotQuestionnairePanel"),Is.True);foreach(var item in new[]{"pilot_rc_01","pilot_sc_01","pilot_accept_01"})Click(item+"_4");Click("PilotQuestionnaireSubmitButton");yield return null;if(condition<2){Assert.That(Active("PilotNeutralTransitionPanel"),Is.True);Click("PilotTransitionContinueButton");yield return null;}}Assert.That(Active("PilotFinalRankingPanel"),Is.True);Click("VoiceOnlyRank1");Click("FloatingOrbRank2");Click("HumanoidAgentRank3");Click("VoiceOnlyPreferred");Input("PilotRankingReason").text="The feedback was easiest to follow.";Click("PilotRankingSubmitButton");yield return null;Assert.That(Active("PilotExperimentCompletionPanel"),Is.True);var coordinator=ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp");var exportArgs=new object[]{null};Assert.That((bool)coordinator.GetType().GetMethod("ExportBundle").Invoke(coordinator,exportArgs),Is.True,exportArgs[0] as string);var auditArgs=new object[]{null};Assert.That((bool)coordinator.GetType().GetMethod("AuditBundle").Invoke(coordinator,auditArgs),Is.True,auditArgs[0] as string);}
        private static void Create(){Click("PilotExperimentButton");}
        private static TMP_InputField Input(string name)=>Resources.FindObjectsOfTypeAll<TMP_InputField>().First(x=>x.name==name&&x.gameObject.scene.IsValid());
        private static Button Button(string name)=>Resources.FindObjectsOfTypeAll<Button>().First(x=>x.name==name&&x.gameObject.scene.IsValid());
        private static void Click(string name)=>Button(name).onClick.Invoke();
        private static bool Active(string name)=>Resources.FindObjectsOfTypeAll<GameObject>().Any(x=>x.name==name&&x.gameObject.scene.IsValid()&&x.activeInHierarchy);
        private static string Label(string button)=>Button(button).GetComponentInChildren<TMP_Text>(true).text;
        private static string Text(string panel){var go=Resources.FindObjectsOfTypeAll<GameObject>().First(x=>x.name==panel&&x.scene.IsValid());return string.Join("\n",go.GetComponentsInChildren<TMP_Text>(true).Select(x=>x.text));}
        private static int EvaluatePilot(string transcript){var type=Type.GetType("SceneTalkVR.Core.GoalEvaluationOrchestrator, Assembly-CSharp");var pilot=Get(ActiveObject("SceneTalkVR.Core.PilotCollectionSessionCoordinator, Assembly-CSharp"),"Workflow");return(int)type.GetMethod("EvaluatePilotUserTranscript").Invoke(null,new[]{pilot,Guid.NewGuid().ToString("N"),transcript,"participant"});}
        private static object Get(object value,string name){var type=value.GetType();return type.GetProperty(name)?.GetValue(value)??type.GetField(name)?.GetValue(value);}
        private static object ActiveObject(string typeName){var type=Type.GetType(typeName);return Resources.FindObjectsOfTypeAll(type).FirstOrDefault();}
        private static void CallActive(string typeName,string method){var value=ActiveObject(typeName);value?.GetType().GetMethod(method)?.Invoke(value,null);}
    }
}
